language: csharp
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    dotnet: 1.0.0-preview2-003121
  - os: osx
    osx_image: xcode7.3
    dotnet: 1.0.0-preview2-003121
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-get update    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-get install jq; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; brew update    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; brew install jq; fi
script:
- dotnet restore
- dotnet pack -c Release -o ./artifacts ./src/AspNetCore.Identity.DocumentDB --version-suffix=$TRAVIS_BUILD_ID
before_deploy:
  - git config --global user.email "travis@felschr.com"
  - git config --global user.name "Travis CI"
  - GIT_TAG=($(jq -r '.version' src/Microsoft.AspNetCore.Identity.DocumentDB/project.json))
  - GIT_TAG=${GIT_TAG::-1}$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$TAGPERM@github.com/FelschR/aspnetcore-identity-documentdb.git --tags
  - ls -R
deploy:
  provider: releases
  api_key:
    secure: AeUGvbn9vT55PBDo2As1DiWD+pfpkYhr0R2gUd43W9ewtS0/UlN7RRAYYuzYPEP4BqGVkphm21e0McPUjUUXGuGvQFHuala18htF9qw0QkHwDdZTXNgbKy+Vsx1ogrixXdDbjg5gW/a+4FzfqC1Xz0pzRcn+MzWbNg1eyB83CdEFyc0rCa1mzjUiHmviqkMk772kwR0y52l7yCMjErLcy7ZOweZaHExI8T9x0svNkDJCJ6PeRYJqlIb4J/bWfi09925Q61EDlADMiBkzI8iIxii0ijFs/r0iGo+orgmmkyzIOkiNe4RG8jg+7/hBblgerXTEHn/iy56aH+kJQSHoxv03XvsL1mbEnozyIEKzeDKbKNjLOqiAFhMgLCvouFtgoW+/IiYHxCF2r8Nm+qN9Vrny+tNaJJ4Rj/VnlHOuAuG2NjdtBsDjswUR55qFnTQObzT8vbaSGDfYs4SjWEeL7myt/phE36vnuR+mz4O3+0fxa8P2JLrUllQGBRaAWSqpn8/cnSnHM+vuURCNpSaHei3emNwyrqdazwpiM0n//NEMSdhmh43n4ujwpDdTjRgxJQbvI6izZbIc0DKLjehznwNm4NYwhap6IHBvzwDGb3zVdLaXUanZ1CI+UEfE/P/Rx4a8eN3BBe/0vHw1DKv8u43AfxqKxW9N6qqauMhDmiQ=
  file: "artifacts/AspNetCore.Identity.DocumentDB.*.nupkg"
  skip_cleanup: true
  on:
    tags: true

