-
  branches:
    except:
      - /feature\/.*/
  # https://www.appveyor.com/docs/branches/#build-on-tags-github-gitlab-and-bitbucket-only
  skip_tags: true
  version: '0.2.0-beta-{build}'
  configuration:
  - Release
  platform: Any CPU
  environment:
    # Don't report back to the mothership
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    GitHubAccessToken:
      secure: InsertEncryptedStringHere
  pull_requests:
    do_not_increment_build_number: true
  install:
  - ps: Start-FileDownload 'https://aka.ms/documentdb-emulator' -FileName 'C:\DocumentDB.Emulator.msi'
  - msiexec.exe /i C:\DocumentDB.Emulator.msi /quiet /qn /log install.log
  - ps: >-
      & "${env:ProgramFiles}\DocumentDB Emulator\DocumentDB.Emulator.exe"

  before_build:
  - ps: >-
      appveyor-retry dotnet restore -v Minimal

      echo "Building ${env:CONFIGURATION}: build ${env:APPVEYOR_BUILD_NUMBER}"
  build_script:
  - ps: dotnet build "src\AspNetCore.Identity.DocumentDB" -c ${env:CONFIGURATION} --version-suffix ${env:APPVEYOR_BUILD_NUMBER}

  test_script:
  - ps: dotnet test test\CoreTests -c ${env:CONFIGURATION}
  - ps: dotnet test test\CoreIntegrationTests -c ${env:CONFIGURATION}

  before_deploy:
  - ps: dotnet pack src\AspNetCore.Identity.DocumentDB -c ${env:CONFIGURATION} -o artifacts --version-suffix ${env:APPVEYOR_BUILD_NUMBER}

  # https://www.appveyor.com/docs/how-to/git-push/
  - ps: git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GitHubAccessToken):x-oauth-basic@github.com`n"
  - ps: git config --global user.email "appveyor@felschr.com"
  - ps: git config --global user.name "AppVeyor"
  - ps: >-
      $GIT_TAG = Get-Content -Raw -Path src/AspNetCore.Identity.DocumentDB/project.json | ConvertFrom-Json | select -ExpandProperty version
      $GIT_TAG = ${GIT_TAG} -replace ".{1}$"
      $GIT_TAG = "${GIT_TAG}${env:APPVEYOR_BUILD_NUMBER}"
  - ps: git tag $GIT_TAG -a -m "Generated tag from AppVeyor from build ${env:APPVEYOR_BUILD_VERSION}"
  - ps: git push --tags
  deploy:
  # https://www.appveyor.com/docs/deployment/github/
  - provider: GitHub
    release: v$(appveyor_build_version)
    description: ''
    auth_token:
      secure: InsertEncryptedStringHere
    artifact: /artifacts\\.*\.nupkg/
    draft: true
    prerelease: true
    on:
      branch: netcore
  # https://www.appveyor.com/docs/deployment/nuget/
  - provider: NuGet
    api_key:
      secure: InsertEncryptedStringHere
    skip_symbols: false
    artifact: /artifacts\\.*\.nupkg/
    on:
      branch: netcore